import type { ModuleDef } from '@/lib/sql/types';

export const allModules: ModuleDef[] = [
  {
    id: 'm1',
    order: 1,
    title: '入门',
    tierKey: 'beginner',
    tierLabel: '小白',
    summary: '把数据"取出来"：SELECT / WHERE / ORDER BY / DISTINCT。',
    lesson: [
      '## 入门：把数据取出来',
      '',
      'SQL 最常做的事就是"查"。一条查询的骨架是：',
      '',
      '```sql',
      'SELECT 列 FROM 表 WHERE 条件 ORDER BY 列;',
      '```',
      '',
      '- `SELECT *` 取所有列；`SELECT a, b` 只取指定列。',
      '- `WHERE` 过滤行，比如 `WHERE age >= 28`。',
      '- `ORDER BY 列 DESC` 倒序排列。',
      '- `DISTINCT` 去掉重复行。',
      '- `LIMIT n` 只取前 n 行。',
      '',
      '> 右边练习场里写完点"运行"，会用真实 Postgres 跑你的 SQL 并对答案。',
    ].join('\n'),
  },
  {
    id: 'm2',
    order: 2,
    title: '关联与聚合',
    tierKey: 'intermediate',
    tierLabel: '初级',
    summary: '把多张表连起来、把多行并成一行：JOIN / GROUP BY / HAVING。',
    lesson: [
      '## 关联与聚合：连表与分组统计',
      '',
      '**JOIN** 把两张表按关联键拼起来：',
      '',
      '```sql',
      'SELECT c.name, o.amount',
      'FROM customers c',
      'JOIN orders o ON o.customer_id = c.id;',
      '```',
      '',
      '- `INNER JOIN` 只留两边都匹配的行；`LEFT JOIN` 保留左表全部，右表缺失处填 `NULL`。',
      '',
      '**聚合**把多行压成一行（`count` / `sum` / `avg` / `max` / `min`），常配 `GROUP BY` 分组：',
      '',
      '```sql',
      'SELECT customer_id, sum(amount) FROM orders GROUP BY customer_id;',
      '```',
      '',
      '- 过滤"分组后的结果"用 `HAVING`；`WHERE` 过滤行、`HAVING` 过滤组。',
      '- 当心 `NULL`：`count(列)` 不会数 `NULL`，`sum`/`avg` 也忽略 `NULL`。',
    ].join('\n'),
  },
  {
    id: 'm3',
    order: 3,
    title: '进阶查询',
    tierKey: 'intermediate',
    tierLabel: '中级',
    summary: '子查询、CTE、集合运算与条件分支：WITH / UNION / CASE。',
    lesson: [
      '## 进阶查询：子查询、CTE、集合、分支',
      '',
      '**子查询**是查询里再套一层查询：',
      '',
      '```sql',
      'SELECT * FROM orders WHERE amount > (SELECT avg(amount) FROM orders);',
      '```',
      '',
      '**CTE（`WITH`）**给子查询起名字，让复杂查询更好读：',
      '',
      '```sql',
      'WITH big AS (SELECT * FROM orders WHERE amount > 100)',
      'SELECT count(*) FROM big;',
      '```',
      '',
      '- `UNION` 合并两个查询结果并去重；`UNION ALL` 不去重（更快）。',
      '- `CASE WHEN ... THEN ... ELSE ... END` 在 `SELECT` 里做条件分支（相当于 if/else）。',
    ].join('\n'),
  },
  {
    id: 'm4',
    order: 4,
    title: '分析利器',
    tierKey: 'intermediate',
    tierLabel: '进阶',
    summary: '窗口函数与日期/字符串——从"会查"到"会分析"的分水岭。',
    lesson: [
      '## 分析利器：窗口函数与日期/字符串',
      '',
      '**窗口函数**能在"不把行合并掉"的前提下做分组计算，是迈向 senior 的关键：',
      '',
      '```sql',
      'SELECT customer_id, amount,',
      '  rank() OVER (PARTITION BY customer_id ORDER BY amount DESC) AS rk',
      'FROM orders;',
      '```',
      '',
      '- `row_number` / `rank` / `dense_rank`：排名。',
      '- `lag` / `lead`：取前一行 / 后一行的值。',
      '- `sum() OVER (ORDER BY ...)`：累计求和（running total）。',
      '- `PARTITION BY` 指定分组、`ORDER BY` 指定窗口内的顺序。',
      '',
      '**日期/字符串**：`EXTRACT(year FROM created_at)` 取年份，配合字符串函数做清洗与分组。',
    ].join('\n'),
  },
];

export function getModuleById(id: string): ModuleDef | undefined {
  return allModules.find((m) => m.id === id);
}
