import type { Exercise } from '@/lib/sql/types';

const SEED = `
CREATE TABLE users (
  id integer PRIMARY KEY,
  name text NOT NULL,
  city text NOT NULL,
  age integer NOT NULL
);
INSERT INTO users (id, name, city, age) VALUES
  (1, '小明', '北京', 25),
  (2, '小红', '上海', 30),
  (3, '小刚', '北京', 28),
  (4, '小美', '广州', 22),
  (5, '阿强', '上海', 35);
`;

export const module1Exercises: Exercise[] = [
  {
    id: 'm1-01',
    moduleId: 'm1',
    title: '选出全部用户',
    difficulty: 1,
    prompt: '用 SELECT 选出 users 表里所有用户的所有列。',
    seedSql: SEED,
    starterSql: 'SELECT ... FROM users;',
    solutionSql: 'SELECT * FROM users;',
    orderMatters: false,
    hints: ['用 * 代表“所有列”。'],
  },
  {
    id: 'm1-02',
    moduleId: 'm1',
    title: '筛选成年达标用户',
    difficulty: 2,
    prompt: '选出 age 大于等于 28 的用户的 name 和 age 两列。',
    seedSql: SEED,
    starterSql: 'SELECT name, age FROM users WHERE ...;',
    solutionSql: 'SELECT name, age FROM users WHERE age >= 28;',
    orderMatters: false,
    hints: ['WHERE 后面写筛选条件。'],
  },
  {
    id: 'm1-03',
    moduleId: 'm1',
    title: '去重城市',
    difficulty: 2,
    prompt: '选出所有用户来自的城市（city），不要有重复。',
    seedSql: SEED,
    starterSql: 'SELECT ... city FROM users;',
    solutionSql: 'SELECT DISTINCT city FROM users;',
    orderMatters: false,
    hints: ['DISTINCT 去掉重复行。'],
  },
  {
    id: 'm1-04',
    moduleId: 'm1',
    title: '按年龄排序',
    difficulty: 2,
    prompt: '选出所有用户的 name 和 age，并按 age 从大到小排序。',
    seedSql: SEED,
    starterSql: 'SELECT name, age FROM users ORDER BY ...;',
    solutionSql: 'SELECT name, age FROM users ORDER BY age DESC;',
    orderMatters: true,
    hints: ['ORDER BY ... DESC 表示降序。'],
  },
  {
    id: 'm1-05',
    moduleId: 'm1',
    title: '取最年长的两位',
    difficulty: 2,
    prompt: '按 age 从大到小，取出前 2 位用户的 name 和 age。',
    seedSql: SEED,
    starterSql: 'SELECT name, age FROM users ORDER BY ... LIMIT ...;',
    solutionSql: 'SELECT name, age FROM users ORDER BY age DESC LIMIT 2;',
    orderMatters: true,
    hints: ['LIMIT N 只取前 N 行。'],
  },
  {
    id: 'm1-06',
    moduleId: 'm1',
    title: '北京的资深用户',
    difficulty: 2,
    prompt: '选出 city 是北京、且 age 大于 25 的用户 name。',
    seedSql: SEED,
    starterSql: 'SELECT name FROM users WHERE ... AND ...;',
    solutionSql: "SELECT name FROM users WHERE city = '北京' AND age > 25;",
    orderMatters: false,
    hints: ['多个条件用 AND 连接。'],
  },
  {
    id: 'm1-07',
    moduleId: 'm1',
    title: '一线城市用户',
    difficulty: 2,
    prompt: '选出 city 属于 北京 或 上海 的用户 name（用 IN）。',
    seedSql: SEED,
    starterSql: 'SELECT name FROM users WHERE city IN (...);',
    solutionSql: "SELECT name FROM users WHERE city IN ('北京', '上海');",
    orderMatters: false,
    hints: ['IN (值1, 值2) 可匹配多个值。'],
  },
  {
    id: 'm1-08',
    moduleId: 'm1',
    title: '按城市再按年龄排序',
    difficulty: 3,
    prompt: '输出 name、city、age，先按 city 升序，同一城市内再按 age 从大到小。',
    seedSql: SEED,
    starterSql: 'SELECT name, city, age FROM users ORDER BY ..., ...;',
    solutionSql: 'SELECT name, city, age FROM users ORDER BY city ASC, age DESC;',
    orderMatters: true,
    hints: ['ORDER BY 可以写多列，用逗号分隔。'],
  },
];
